## LESSON ON NUMPY AND PANDAS

* A quick example on how to import a video from youtube inside JupyterNotebook

To run the video, the video ID is needed, which is after the equal to in the link of the video

```python
from IPython.display import YouTubeVideo
YouTubeVideo("ukzFI9rgwfU", width = 400, height = 300)  
```

How to link somethig on the web with python. This is a link to one of my papers

 __[Link to my paper](https://pubmed.ncbi.nlm.nih.gov/35393704/)__



In [6]:
import numpy as np
import pandas as pd

In [21]:
#creating a numpy array in one dimensional

matrix_a = np.array([2,4,5,6,7,9,11]) 
matrix_b = np.array ([3,4,5,6,11,45,76])

matrix_c = matrix_b * matrix_a
matrix_c
matrix_c.shape
matrix_c[0:4]



array([ 6, 16, 25, 36])

In [24]:
#two dimensional array

b = np.zeros((2,2))
b[0][0] = 2.0
b

array([[2., 0.],
       [0., 0.]])

In [27]:
#Function in array
matrix_full = np.full((3,3), 7)
matrix_full

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])