## LESSON 2 - Array Manipulation

* Manipulating array shapes with the reshape() function

```python
arr_reshape = np.arange (16)
arr_reshape
arr_new = arr_reshape.reshape(4,4)
arr_new
```
this code gives a 4x4 matrix

* The flatten() function flattens any n-dimension array into a one-dimensional array

```python
arr_flat = arr_new.flatten()
arr_flat
```

* The transpose() function will transpose a matrix 

```python
arr_new.transpose()
```
* The resize() function can be used to resize an already shaped matrix 

```python
arr_new.resize(2,8)
```

* Slicing Numpy arrays

To slice an array

```python 
array[2:8] #slice from index 2 to 8
array[2:8:2] #slice from index 2 to 8, but jump by 2
array[-4:] #slice from the back of the array
```

In [2]:
import numpy as np
import pandas as pd

In [5]:
#Reshape function (reshape())

arr_reshape = np.arange (16)
arr_reshape
arr_new = arr_reshape.reshape(4,4)
arr_new

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:

arr_new.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [14]:

arr_reshape.transpose()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [16]:
arr_new.resize(2,8)

In [17]:
arr_new


array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [18]:
arr_reshape

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [19]:
arr_reshape[3:6]

array([3, 4, 5])

In [20]:
arr_reshape[-4:]

array([12, 13, 14, 15])

In [21]:
arr_reshape[3:9: 3]

array([3, 6])

In [ ]:
data = 